services:
  - type: web
    name: logivice-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: TABLEAU_TOKEN_NAME
        sync: false
      - key: TABLEAU_TOKEN_VALUE
        sync: false
      - key: TABLEAU_SERVER
        sync: false
      - key: TABLEAU_SITE
        sync: false
      - key: ADMIN_PASSWORD
        generateValue: true
